services:
  app:
    build: .
    image: timetable-be
    env_file:
      - .env
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - default

networks:
  default:
    driver: bridge