DROP INDEX IF EXISTS idx_faculty_school_id;
DROP INDEX IF EXISTS idx_field_faculty_id;
DROP INDEX IF EXISTS idx_subject_faculty_id;
DROP INDEX IF EXISTS idx_class_field_id;
DROP INDEX IF EXISTS idx_semester_faculty_id;
DROP INDEX IF EXISTS idx_subject_instance_semester_id;
DROP INDEX IF EXISTS idx_subject_instance_subject_id;
DROP INDEX IF EXISTS idx_si_to_user_user_id;
DROP INDEX IF EXISTS idx_si_to_user_si_id;
DROP INDEX IF EXISTS idx_subject_week_si_id;
DROP INDEX IF EXISTS idx_note_school_id;
DROP INDEX IF EXISTS idx_note_user_id;
DROP INDEX IF EXISTS idx_note_subject_id;

ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "u_s_fk";
ALTER TABLE "faculties" DROP CONSTRAINT IF EXISTS "fa_s_fk";
ALTER TABLE "fields" DROP CONSTRAINT IF EXISTS "fi_fa_fk";
ALTER TABLE "subjects" DROP CONSTRAINT IF EXISTS "su_fa_fk";
ALTER TABLE "classes" DROP CONSTRAINT IF EXISTS "c_fi_fk";
ALTER TABLE "semesters" DROP CONSTRAINT IF EXISTS "se_fa_fk";
ALTER TABLE "subject_instance_types" DROP CONSTRAINT IF EXISTS "sit_s_fk";
ALTER TABLE "subject_instances" DROP CONSTRAINT IF EXISTS "si_sit_fk";
ALTER TABLE "subject_instances" DROP CONSTRAINT IF EXISTS "si_se_fk";
ALTER TABLE "subject_instances" DROP CONSTRAINT IF EXISTS "si_su_fk";
ALTER TABLE "si_to_users" DROP CONSTRAINT IF EXISTS "stu_u_fk";
ALTER TABLE "si_to_users" DROP CONSTRAINT IF EXISTS "stu_si_fk";
ALTER TABLE "subject_weeks" DROP CONSTRAINT IF EXISTS "sw_si_fk";
ALTER TABLE "notes" DROP CONSTRAINT IF EXISTS "n_s_fk";
ALTER TABLE "notes" DROP CONSTRAINT IF EXISTS "n_u_fk";
ALTER TABLE "notes" DROP CONSTRAINT IF EXISTS "n_su_fk";
ALTER TABLE "one_offs" DROP CONSTRAINT IF EXISTS "oo_u_fk";
ALTER TABLE "one_offs" DROP CONSTRAINT IF EXISTS "oo_c_fk";
ALTER TABLE "one_off_to_users" DROP CONSTRAINT IF EXISTS "ootu_u_fk";
ALTER TABLE "one_off_to_users" DROP CONSTRAINT IF EXISTS "ootu_oo_fk";

DROP TABLE IF EXISTS "refresh_tokens";
DROP TABLE IF EXISTS "one_off_to_users";
DROP TABLE IF EXISTS "one_offs";
DROP TABLE IF EXISTS "notes";
DROP TABLE IF EXISTS "subject_weeks";
DROP TABLE IF EXISTS "si_to_users";
DROP TABLE IF EXISTS "subject_instances";
DROP TABLE IF EXISTS "subject_instance_types";
DROP TABLE IF EXISTS "semesters";
DROP TABLE IF EXISTS "classes";
DROP TABLE IF EXISTS "subjects";
DROP TABLE IF EXISTS "fields";
DROP TABLE IF EXISTS "faculties";
DROP TABLE IF EXISTS "schools";
DROP TABLE IF EXISTS "users";